baseurl: /inet-showcases
showallpages: true
data_dir: _docs/_data
includes_dir: _docs/_includes
layouts_dir: _docs/_layouts
exclude: [
"general/dynamic/results",
"general/pcaprecording/results",
"routing/manet/results",
"visualizer/advanced/results",
"visualizer/datalinkactivity/results",
"visualizer/earth/results",
"visualizer/environment/results",
"visualizer/filtering/results",
"visualizer/ieee80211/results",
"visualizer/info/results",
"visualizer/instrument/results",
"visualizer/interfacetable/results",
"visualizer/linkbreak/results",
"visualizer/mobility/results",
"visualizer/networknode/results",
"visualizer/networkpathactivity/results",
"visualizer/obstacleloss/results",
"visualizer/osgdemo/results",
"visualizer/packetdrop/results",
"visualizer/physicallinkactivity/results",
"visualizer/radiomediumactivity/results",
"visualizer/routingtable/results",
"visualizer/statistic/results",
"visualizer/styling/results",
"visualizer/transportconnection/results",
"visualizer/transportpathactivity/results",
"wireless/coexistence/results",
"wireless/crosstalk/results",
"wireless/errorrate/results",
"wireless/handover/results",
"wireless/hiddennode/results",
"wireless/ieee80211levelofdetail/results",
"wireless/ieee802154/results",
"wireless/infrastructure/results",
"wireless/levelofdetail/results",
"wireless/multiradio/results",
"wireless/pathloss/results",
"wireless/power/results",
"wireless/qos/results",
"wireless/ratecontrol/results",
"wireless/scaling/results",
"wireless/sensornetwork/results",
"wireless/throughput/results"
]

collections:
  docs:
    output: true
    permalink: /:path
